### ISSUE TITLE
Cannot get it working

### ISSUE THREAD

**Issue by GraphGrail** [pydanny/django-mongonaut#76]
Could anyone release full preconfigured django install with working admin panel and instructions how to loging.
http://127.0.0.1:8000/mongonaut/  - You do not have permissions to access this content.
Also http://127.0.0.1:8000/ - white page with title django-mongonaut Blog Example, no posts, but i have added posts from Robomongo.

**Comment by pydanny** [comment]
Apologies, but we do not have resources or time to come up with, much less maintain a Vagrant/Docker install with working MongoDB, Django, and django-mongonaut setup. I humbly suggest that once you figure this out, that you create a GitHub repo for your Vagrant/Docker install. Then, we'll link to it from this repo.

As for your inability to see content or access content, have you:

* Authenticated into Mongonaut?
* Used Robonaut to define documents tied to the mongoengine definitions inside of the blog examples?
