### ISSUE TITLE
Any plans on upgrading for django 1.8.x?

### ISSUE THREAD

**Issue by robintiwari** [pydanny/django-mongonaut#81]
For Django 1.7, mongonaut works fine, however for 1.8.x it is not working specifically edit part. I noticed the dictionary field "_data" for the document only has key-value pair of "id" and all the other fields are missing.

**Comment by garrypolley** [comment]
We're open to a pull request to make this library work with Django 1.8.x.  However, I do not think myself or @pydanny have the time to uplift what would be needed to support 1.8.x versions of Django.

**Comment by Phlip** [comment]
so if I were a Django 1.8 user who throws in some `mongonaut`, I should see more than an empty page with the name of my "application" in it, right? That's all I see, and I don't know how to use the URLs to fish around. Am I supposed to put a table name in the URL?

I'm asking bc I don't know if my symptom needs a new ticket. No going in after the feature with a debugger

**Comment by garrypolley** [comment]
If it helps here are our [urls](https://github.com/pydanny/django-mongonaut/blob/master/mongonaut/urls.py)

**Comment by pydanny** [comment]
See https://github.com/pydanny/django-mongonaut/blob/master/README.rst#this-project-is-unsupported

**Comment by Phlip** [comment]
I will take a look under the hood, in soft time between shifts​. doing 1.8
& mongo like it ain't no thang

**Comment by Phlip** [comment]
occurs to me I can also start a small accessory 1.7 seven project, and
project the results. chat mode off
